# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Category.create(name: "IT")
Category.create(name: "Software")
Category.create(name: "SaaS")
Category.create(name: "Startup")
network_category = Category.create(name: "Network")
Category.create(name: "Social Media")
Category.create(name: "Twitter")
Category.create(name: "Facebook")
Category.create(name: "Foursquare")
Category.create(name: "Cooking")
Category.create(name: "Sweet")
Category.create(name: "Sour")
Category.create(name: "Bitter")
Category.create(name: "Salt")
umami_category = Category.create(name: "Umami")
Category.create(name: "Food")
Category.create(name: "Recipe")
Category.create(name: "Homemade")
Category.create(name: "Bio")
Category.create(name: "Sport")
Category.create(name: "Football")
Category.create(name: "Tennis")
Category.create(name: "Golf")
Category.create(name: "Basketball")
Category.create(name: "Furniture")
Category.create(name: "Couch")
Category.create(name: "Chair")
Category.create(name: "Designer")
Category.create(name: "Movies")
Category.create(name: "Films")
Category.create(name: "Series")
Category.create(name: "Actor")
Category.create(name: "Box-office")
Category.create(name: "Game")
Category.create(name: "GTA5")
Category.create(name: "Xbox")
Category.create(name: "Playstation")
Category.create(name: "E-learning")
Category.create(name: "Duolingo")
Category.create(name: "Coursera")
Category.create(name: "Udemy")
Category.create(name: "Socrative")
Category.create(name: "Philosophy")
Category.create(name: "Plato")
Category.create(name: "Nietsche")
Category.create(name: "Kant")
Category.create(name: "Socrates")
Category.create(name: "Music")
Category.create(name: "Artist")
Category.create(name: "Guitar")
Category.create(name: "Bass")
Category.create(name: "Drum")
Category.create(name: "Sampler")
Category.create(name: "Violin")
Category.create(name: "Piano")
Category.create(name: "Rock and Roll")
Category.create(name: "Hiphop")
Category.create(name: "Blues")
Category.create(name: "Jazz")
Category.create(name: "Classical")
Category.create(name: "Jupiler")
Category.create(name: "Heineken")
Category.create(name: "Grolsch")
Category.create(name: "Budweiser")
Category.create(name: "Becks")
Category.create(name: "Space")
Category.create(name: "Gravity")
Category.create(name: "ISS")
Category.create(name: "Astronaut")
Category.create(name: "Moon")
Category.create(name: "Kevin Spacey")
Category.create(name: "Sun")
Category.create(name: "Tech")
Category.create(name: "Technology")
Category.create(name: "Disrupt")
hackathon_category = Category.create(name: "Hackathon")
Category.create(name: "Psychology")
Category.create(name: "Zimbardo")
Category.create(name: "Cognition")
Category.create(name: "Copenhagen")
Category.create(name: "Social Psychology")
programming_category = Category.create(name: "Programming")
Category.create(name: "Python")
Category.create(name: "CSS")
Category.create(name: "HTML")
Category.create(name: "Ruby")
Category.create(name: "Ruby on Rails")
Category.create(name: "Framework")
Category.create(name: "NodeJS")
Category.create(name: "Javascript")
Category.create(name: "Java")
Category.create(name: "Apple")
Category.create(name: "iPhone")
Category.create(name: "iPad")
Category.create(name: "Coffescript")
Category.create(name: "PHP")
Category.create(name: "C-sharp")
Category.create(name: "Scala")
Category.create(name: "Whitespace")
Category.create(name: "Coffee")
Category.create(name: "Coffee beans")
Category.create(name: "Barista")
Category.create(name: "Grunge")
Category.create(name: "Deephouse")
Category.create(name: "Techno")
berlin_category = Category.create(name: "Berlin")
Category.create(name: "Homo")
Category.create(name: "Gay")
Category.create(name: "Cats")
Category.create(name: "Dogs")
Category.create(name: "Baby")
Category.create(name: "Drinks")
Category.create(name: "Whiskey")
Category.create(name: "Gin")
Category.create(name: "Wine")
Category.create(name: "Cheese")
Category.create(name: "marshall")
Category.create(name: "Army")
Category.create(name: "America")
Category.create(name: "Europe")
Category.create(name: "EU")
Category.create(name: "UN")
Category.create(name: "Politics")
Category.create(name: "Obama")
Category.create(name: "Barack Obama")
Category.create(name: "UK")
Category.create(name: "The Netherlands")
Category.create(name: "Germany")
Category.create(name: "France")
Category.create(name: "Paris")
Category.create(name: "Spain")
Category.create(name: "Barcelona")
Category.create(name: "Malaga")
Category.create(name: "Madrid")
Category.create(name: "Italy")
Category.create(name: "Rome")
Category.create(name: "Colosseum")
Category.create(name: "Greece")
Category.create(name: "Athens")
Category.create(name: "Poland")
Category.create(name: "Russia")
Category.create(name: "Moskow")
Category.create(name: "Japan")
Category.create(name: "Tokyo")
china_category = Category.create(name: "China")
lufthansa_category = Category.create(name: "Lufthansa")
Category.create(name: "Dropbox")
Category.create(name: "Chrome")
Category.create(name: "Google")
Category.create(name: "Fire")
Category.create(name: "Pinterest")
Category.create(name: "Defacto")

jesse=User.create(name:"jesse", email:"j.terpstra@defacto.nl")
marthyn=User.create(name:"marthyn", email:"marthyn@live.nl")
Device.create(token:"977919c66b18a4f4737c07768a33cb323c9ebe89e5eaaf3524a69219724ec331", user_id:marthyn.id)
UserCategory.create(category_id:network_category.id, user_id:marthyn.id)
question1 = Question.create(question:"How can I supply good wifi for a Hackathon?", category_id:network_category.id, user_id:jesse.id)
Request.create(user_id: marthyn.id, question_id: question1.id )

UserCategory.create(category_id:umami_category.id, user_id:marthyn.id)
question2 = Question.create(question:"What is a good way to learn to tast umami?", category_id:umami_category.id, user_id:jesse.id)
Request.create(user_id: marthyn.id, question_id: question2.id )

UserCategory.create(category_id:china_category.id, user_id:marthyn.id)
question3 = Question.create(question:"Can people in China download and use google chrome?", category_id:china_category.id, user_id:jesse.id)
Request.create(user_id: marthyn.id, question_id: question3.id )

UserCategory.create(category_id:lufthansa_category.id, user_id:marthyn.id)
question4 = Question.create(question:"How is flying with Lufthansa, is it any good?", category_id:lufthansa_category.id, user_id:jesse.id)
Request.create(user_id: marthyn.id, question_id: question4.id )

UserCategory.create(category_id:programming_category.id, user_id:marthyn.id)
Question.create(question:"What’s an average programmer salary in Berlin?", category_id:programming_category.id, user_id:jesse.id, answer: "€5000", user_answer_id: marthyn.id)


UserCategory.create(category_id:berlin_category.id, user_id:marthyn.id)
Question.create(question:"Whats the cheapest hostel next to Arena?", category_id:berlin_category.id, user_id:jesse.id, user_answer_id: marthyn.id, answer:"All in hotel")

UserCategory.create(category_id:hackathon_category.id, user_id:marthyn.id)
Question.create(question:"When is the next big Hackathon in Berlin?", category_id:hackathon_category.id, user_id:jesse.id, answer: "Disrupt 2014!", user_answer_id:marthyn.id)

